These two scripts show what happens if we do not use finally and the exception has not been handled in the try-catch
